version: '3.8'

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
    ports:
      - "2323:8080"
  db:
    build: ./db
    container_name: db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 4406:3306
    networks:
      - application
  app:
    build: ./app
    container_name: app
    env_file:
      - ./.app.env
    ports:
      - 3000:4567
    volumes:
      - ./aozorabunko:/aozorabunko
      - ./app:/app
    networks:
      - application
  mysql_app:
    build: ./mysql_app
    container_name: mysql_app
    env_file:
      - ./.mysql.env
    ports:
      - 4000:4567
    volumes:
      - ./aozorabunko:/aozorabunko
      - ./mysql_app:/app
    networks:
      - application

networks:
  application:
    driver: bridge
