version '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: bluesky
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  app:
    build: ./app/
    container_name: app
    volumes:
      - ./app:/src
      - ./aozorabunko:/aozorabunko
