version: '3.3'

services:
  db:
    build: ./db
    container_name: db
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      TZ: 'Asia/Tokyo'
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 4406:3306
    networks:
      - application
  app:
    build: ./app
    container_name: app
    env_file:
      - ./.env
    ports:
      - 3000:4567
    volumes:
      - ./aozorabunko:/aozorabunko
      - ./app:/app
    networks:
      - application

networks:
  application:
    driver: bridge
