version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - application
  app:
    build: ./app
    container_name: app
    ports:
      - 4567:4567
    volumes:
      - ./aozorabunko:/aozorabunko
    networks:
      - application

networks:
  application:
    driver: bridge
