# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'mini_portile'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri'
gem 'puma'
gem 'haml'

gem 'mysql2'
gem 'sequel'
# gem "rails"
