# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "sinatra"
gem "nokogiri"
gem "puma"

gem 'rom-repository'
gem 'rom-sql'
gem 'mysql2'
# gem "rails"
